description = """
  Global ocean triangular mesh, \
  with a target mesh size set to a uniform field with a value of 300km \
  for the interior of the domain and 10km for coastlines. \
  All units are meters. \
  The code used the seamsh Python package by Jonathan Lambrechts \
  and a description of the algorithm can be found at \
  https://doi.org/10.1007/s10236-008-0148-3 \
  The code uses coastline shapefiles, which are taken from \
  NaturalEarth physical vector 1:10m coastline files \
  (version 4.1.0, accessed on 21/01/2026).
  """
license = """
  The mesh is licensed under the Creative Commons \
  Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0). You \
  may obtain a copy of the License at: \
  https://creativecommons.org/licenses/by-nc-sa/4.0/. \
  Made with Natural Earth. Free vector and raster map data @ naturalearthdata.com
  """

[mesh]
smoothness = 0.3

[domain]
filepath = "data/geometry/ne_10m_coastline/ne_10m_coastline.shp"
physical_name_field = "featurecla"
curve_type = "bspline"
sampling = 5_000.0

[coarsen_boundaries]
mesh_size = 10_000.0

# For bathymetry and its hessian fields, Lambrecths et al use 25 km as a minimum mesh size,
# and 30 for the shore proximity criterium. However, this would result in a mesh too fine for our purposes.
[[fields]]
name = "shore_proximity"
filepath = "data/geometry/ne_10m_coastline/ne_10m_coastline.shp"
physical_name_field = "featurecla"
curve_type = "bspline"
sampling = 5_000.0
field_min = 0.0
field_max = 500_000.0
size_min = 100_000.0
size_max = 200_000.0

[[fields]]
name = "bathymetry"
filepath = "data/dataset/glorys12_static_res-0p0625_levels-10.zip"
var_name = "deptho"
q_low = 0.1
q_high = 0.9
size_min = 100_000.0
size_max = 500_000.0