[domain]
physical_name_field = "featurecla"
curve_type = "bspline"

[coarsen_boundaries]
mesh_size = 10_000.0

[field]
name = "ShoreProximityField"
sampling = 5_000.0
field_min = 0.0
field_max = 500_000.0
size_min = 30_000.0
size_max = 200_000.0

[save]
projection = "cartesian"