#! /usr/bin/env bash
#
# Notice: the deactivation script should be sourced, not executed.

# Source modules.sh if it has not yet
if [[ ! -v LEONARDO_MODULES_DEFINED ]]; then
    ROOT=$(git rev-parse --show-toplevel)
    source "${ROOT}/leonardo/environment/modules.sh"
fi

# It should be enough to deactivate the python and then the spack environments, finally unload modules
deactivate
spack env deactivate

unload_modules