provider = 'gcs'
type = 'static'

[[datasets]]
url = 'gs://weatherbench2/datasets/era5/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr'
variables = ['land_sea_mask', 'geopotential_at_surface']

[[postprocess]]
name = 'drop_vars'
names = ['time', 'level']

[[postprocess]]
name = 'regrid'
method = 'conservative'
latitude_dim = 'latitude'
longitude_dim = 'longitude'

[postprocess.kwargs]
skipna = true

[postprocess.grid]
south = -90.0
north = 90.0
west = 0.0
east = 359.0
resolution_lat = 1.0
resolution_lon = 1.0

[[postprocess]]
name = 'flip'
dim = 'latitude'

[[postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

[save]
consolidated = true
chunk = {lat = -1, lon = -1}
compressor = {cname = 'lz4', clevel = 1}
