# TODO: choose a good input chunk size for performance.
provider = 'gcs'
type = 'timeseries'
start = 1993-01-01T00:00:00
end = 2021-07-02T00:00:00

[temporary]
step = '10 W'

[slurm_array]
step = '40 W'

[[datasets]]
url = 'gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3'
variables = ['10m_u_component_of_wind',
             '10m_v_component_of_wind',
             'instantaneous_10m_wind_gust',
             '2m_temperature',
             '2m_dewpoint_temperature',
             'surface_pressure',
             'surface_solar_radiation_downwards',
             'surface_thermal_radiation_downwards',
             'total_precipitation']

[[postprocess]]
name = 'isel'
level = 0
drop = true

[[postprocess]]
name = 'clip_negative'
variables = [
    'surface_solar_radiation_downwards',
    'surface_thermal_radiation_downwards',
    'total_precipitation']

[[postprocess]]
name = 'resample'
time = '1 D'
reduce = 'mean'

[[postprocess]]
name = 'chunk'
time = 'auto'
latitude = -1
longitude = -1

# TODO: choose a good output chunk size.
[save]
consolidated = true
chunk = {time = 1, latitude = -1, longitude = -1}
compressor = {cname = 'lz4', clevel = 1}
