[[datasets]]
url = 'gs://weatherbench2/datasets/era5/1959-2022-1h-360x181_equiangular_with_poles_conservative.zarr'
variables = ['10m_u_component_of_wind',
             '10m_v_component_of_wind',
             '2m_temperature']

[postprocess.chunk]
time = 2

[postprocess.resample]
time = '1 D'
