provider = 'cm'
type = 'timeseries'
start = 2024-01-01T00:00:00
end = 2025-01-04T00:00:00

[temporary]
step = '4 W'

[slurm_array]
step = '13 W'

[[datasets]]
dataset_id = 'cmems_mod_glo_phy_anfc_0.083deg_P1D-m'
dataset_version = '202406'
variables = ['mlotst', 'zos', 'sithick', 'siconc', 'usi', 'vsi']
dataset_part = 'default'
service = 'arco-geo-series'

[[datasets]]
dataset_id = 'cmems_mod_glo_phy-so_anfc_0.083deg_P1D-m'
dataset_version = '202406'
variables = ['so']
dataset_part = 'default'
service = 'arco-geo-series'

[[datasets]]
dataset_id = 'cmems_mod_glo_phy-thetao_anfc_0.083deg_P1D-m'
dataset_version = '202406'
variables = ['thetao']
dataset_part = 'default'
service = 'arco-geo-series'

[[datasets]]
dataset_id = 'cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m'
# dataset_version = '202311'
# TODO: could be bottomT useful?
variables = ['uo', 'vo']
dataset_part = 'default'
service = 'arco-geo-series'

[[postprocess]]
name = 'isel'
depth = [0, 4, 8, 12, 16, 20, 24, 28, 32, 34]

[[postprocess]]
name = 'clip_negative'
variables = ['so', 'mlotst', 'sithick', 'siconc']

[[postprocess]]
name = 'transpose'
dims = ['time', 'depth', 'latitude', 'longitude']

[[postprocess]]
name = 'chunk'
time = 'auto'
depth = -1
latitude = -1
longitude = -1

[[postprocess]]
name = 'regrid'
method = 'conservative'
latitude_dim = 'latitude'
longitude_dim = 'longitude'

[postprocess.kwargs]
skipna = true
output_chunks = {time = 'auto', depth = -1, latitude = -1, longitude = -1}

[postprocess.grid]
south = -90.0
north = 90.0
west = 0.0
east = 359.75
resolution_lat = 0.25
resolution_lon = 0.25

[[postprocess]]
name = 'astype'
casting = 'same_kind'
dtype = 'float32'

[save]
consolidated = true
chunk = {time = 1, depth = -1, latitude = -1, longitude = -1}
compressor = {cname = 'lz4', clevel = 1}
