provider = 'cm'
type = 'static'

[[datasets]]
dataset_id = 'cmems_mod_glo_phy_my_0.083deg_static'
dataset_version = '202311'
variables = ['deptho', 'depth']
dataset_part = 'bathy'
service = 'static-arco'

[[postprocess]]
name = 'isel'
depth = [0, 4, 8, 12, 16, 20, 24, 28, 32, 34]

[[postprocess]]
name = 'transpose'
dims = ['depth', 'latitude', 'longitude']

[[postprocess]]
name = 'chunk'
depth = -1
latitude = -1
longitude = -1

[[postprocess]]
name = 'regrid'
method = 'conservative'

[postprocess.kwargs]
skipna = true
latitude_coord = 'latitude'

[postprocess.grid]
south = -90.0
north = 90.0
west = 0.0
east = 359.75
resolution_lat = 0.25
resolution_lon = 0.25

[[postprocess]]
name = 'astype'
dtype = 'float32'
casting='same_kind'

[save]
consolidated = true
chunk = {depth = -1, latitude = -1, longitude = -1}
compressor = {cname = 'lz4', clevel = 1}
