[[datasets]]
dataset_id = 'cmems_mod_glo_phy_my_0.083deg_P1D-m'
dataset_version = '202311'
variables = ['uo', 'vo', 'so', 'thetao', 'zos']
dataset_part = 'default'
service = 'arco-geo-series'

[postprocess.isel]
depth = [0, 4, 8, 12, 16, 20, 24, 28, 32, 34]

[postprocess.regrid]
method = 'conservative'
kwargs = {skipna = true, latitude_coord='latitude'}

[postprocess.regrid.grid]
south = -90.0
north = 90.0
west = -180.0
east = 179.0
resolution_lat = 1.0
resolution_lon = 1.0

[postprocess.chunk]
time = 2
depth = 5
