# FIXME: some of the operations performed here should be moved to the download phase, or the two phases should be merged
start = 1993-01-01T00:00:00
end = 2021-07-01T00:00:00

[slurm_array]
step = '13 W'

[[datasets]]
name = 'era'
file = 'era5_tres-1d_res-0p25_levels-1'
kwargs = {parallel = true, drop_variables = 'runoff'}

[[datasets.postprocess]]
name = 'flip'
dim = 'latitude'

[[datasets.postprocess]]
name = 'time_shift'
quantity = '1D'

[[datasets.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

[[datasets.postprocess]]
name = 'rescale'

[datasets.postprocess.values]
total_precipitation = 24.0
surface_solar_radiation_downwards = 24.0
surface_thermal_radiation_downwards = 24.0

[[datasets.postprocess]]
name = 'clip_negative'
variables = [
    'instantaneous_10m_wind_gust',
    'surface_solar_radiation_downwards',
    'surface_thermal_radiation_downwards',
    'total_precipitation']

[[datasets.postprocess]]
name = 'rename'

[datasets.postprocess.name_dict]
2m_temperature = '2t'
2m_dewpoint_temperature = '2d'
surface_pressure = 'sp'
surface_solar_radiation_downwards = 'ssrd'
surface_thermal_radiation_downwards = 'strd'
total_precipitation = 'tp'
10m_u_component_of_wind = '10u'
10m_v_component_of_wind = '10v'
instantaneous_10m_wind_gust = 'i10fg'

[[datasets]]
name = 'era_static'
file = 'era5_static_res-0p25_levels-1'
variables = ['land_sea_mask', 'geopotential_at_surface']

[[datasets.postprocess]]
name = 'rename'
name_dict = {land_sea_mask = 'lsm', geopotential_at_surface = 'z'}

[[datasets]]
name = 'glorys'
file = 'glorys12_tres-1d_res-0p25_levels-10'
kwargs = {parallel = true}

[datasets.mask]
file = 'glorys12_static_res-0p25_levels-10'
variable = 'glorys_mask'

[[datasets.mask.postprocess]]
name = 'get_sea_mask'
bathymetry = 'deptho'
depth_coordinate = 'depth'
depth_dim = 'depth'
mask_name = 'glorys_mask'

[[datasets.mask.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon', depth = 'level'}
set_new_coordinate = {'level' = [0, 4, 8, 12, 16, 20, 24, 28, 32, 34]}

[[datasets.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon', depth = 'level'}
set_new_coordinate = {'level' = [0, 4, 8, 12, 16, 20, 24, 28, 32, 34]}

[[datasets.postprocess]]
name = 'fill'
variables = ['usi', 'vsi', 'sithick', 'siconc']

[[datasets.postprocess]]
name = 'gauss_fill'
variables = ['so', 'thetao', 'vo', 'uo', 'mlotst', 'zos']
sigma = 1.0
radius = 4
mode = 'mirror'
output = 'float32'

[[datasets.postprocess]]
name = 'clip_negative'
variables =  ['so', 'mlotst', 'sithick', 'siconc']

[[datasets]]
name = 'glofas'
file = 'glofas_tres-1d_res-0p25_levels-1'
kwargs = {parallel = true}

[datasets.mask]
file = 'glofas_static_res-0p25_levels-1'
variable = 'glofas_mask'

[[datasets.mask.postprocess]]
name = 'get_land_mask'
variable = 'uparea'
mask_name = 'glofas_mask'

[[datasets.postprocess]]
name = 'gauss_fill'
variables = ['dis24']
sigma = 1.0
radius = 4
mode = 'mirror'
output = 'float32'

[[datasets.postprocess]]
name = 'clip_negative'
variables = ['dis24']

[[datasets.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

[[datasets]]
name = 'waverys'
file = 'waverys_tres-1d_res-0p25_levels-1'
kwargs = {parallel = true}

[datasets.mask]
file = 'waverys_static_res-0p25_levels-1'
variable = 'waverys_mask'

[[datasets.mask.postprocess]]
name = 'get_land_mask'
variable = 'deptho'
mask_name = 'waverys_mask'

[[datasets.mask.postprocess]]
name = 'rename'
name_dict = {deptho = 'waverys_deptho'}

[[datasets.mask.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

[[datasets.postprocess]]
name = 'rename_coordinates'
name_dict = {latitude = 'lat', longitude = 'lon'}

[[datasets.postprocess]]
name = 'fill'
variables = ['vhm0', 'vtm02', 'vmdr', 'vsdx', 'vsdy']

[[datasets.postprocess]]
name = 'clip_negative'
variables = ['vhm0', 'vtm02']

[[datasets.postprocess]]
name = 'rename'
name_dict = {vhm0 = 'swh', vtm02 = 'swp', vsdx = 'usd', vsdy = 'vsd', vmdr = 'mwd'}

[save]
consolidated = true
chunk = {time = 1, level = 1, lat = -1, lon = -1}
compressor = {cname = 'lz4', clevel = 1}
