seed = 42
target_lead_times = "1d"
description = """
  GraphCast model for the ocean at 1deg resolution, \
  5 depth levels, and a reduced set of atmospheric forcing variables. \
  This model is trained on ARCO-OCEAN data from 1993 to 2021, \
  and can be causally evaluated on 2022 and later years. \
  It uses a global ocean mesh with uniform target mesh size of 300 km. \
  GraphCast is described in the paper \
  `GraphCast: Learning skillful medium-range global weather forecasting`(https://arxiv.org/abs/2212.12794). \
  For a description of the ocean model, see README at \
  https://github.com/stefanocampanella/graphcast.
  """
license = """
  The model weights are licensed under the Creative Commons \
  Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0). You \
  may obtain a copy of the License at: \
  https://creativecommons.org/licenses/by-nc-sa/4.0/. \
  The weights were trained on ARCO-OCEAN data, see README at \
  https://github.com/inogs/arco-ocean \
  for attribution statement. \
  """

[task]
input_variables = [
    "zos",
    "thetao",
    "so",
    "uo",
    "usi",
    "vo",
    "vsi",
    "deptho",
    "glorys_mask",
]
target_variables = [
    "zos",
    "thetao",
    "so",
    "uo",
    "usi",
    "vo",
    "vsi",
]
forcing_variables = [
    "10u",
    "10v",
    "2t",
    "year_progress_sin",
    "year_progress_cos",
]
levels = [0, 4, 8, 12, 16]
input_duration = "2d"

[model]
latent_size = 512
gnn_msg_steps = 16
hidden_layers = 1
radius_query_fraction_edge_length = 0.6
per_variable_weights = {}

[mesh]
filepath = "data/geometry/uniform_mini.msh"
mesh_size_tag_name = "MeshSize"
step = 0

[dataset]
filepath = "data/dataset/dataset_tres-1d_res-1_levels-10_arco"
timesteps = 3
mask_name = 'glorys_mask'