description = """
  GraphCast model for the ocean at 0.25deg resolution, \
  10 depth levels, and a full set of atmospheric and hydrological forcing variables. \
  This model is trained on ARCO-OCEAN data from 01-01-1993 to 30-06-2019, \
  and can be causally evaluated on later years. \
  It uses a global ocean mesh with uniform target mesh size of 120 km. \
  GraphCast is described in the paper \
  `GraphCast: Learning skillful medium-range global weather forecasting`(https://arxiv.org/abs/2212.12794). \
  For a description of the ocean model, see README at \
  https://github.com/stefanocampanella/graphcast.
  """
license = """
  The model weights are licensed under the Creative Commons \
  Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0). You \
  may obtain a copy of the License at: \
  https://creativecommons.org/licenses/by-nc-sa/4.0/. \
  The weights were trained on ARCO-OCEAN data, see README at \
  https://github.com/inogs/arco-ocean \
  for attribution statement. \
  """
training_steps = 32768
seed = 42

[task]
input_variables = [
    "zos",
    "mlotst",
    "thetao",
    "siconc",
    "sithick",
    "so",
    "uo",
    "usi",
    "vo",
    "vsi",
    "deptho",
    "z",
    "glofas_mask",
    "glorys_mask",
    "lsm",
    "uparea",
    "waverys_deptho",
    "waverys_mask",
    "year_progress_sin",
    "year_progress_cos",
]
# Sea-ice variables look hard to forecast, we momentarily exclude them from forecasts
target_variables = [
    "zos",
    "mlotst",
    "thetao",
    "so",
    "uo",
    "vo",
]
forcing_variables = [
    "10u",
    "10v",
    "2d",
    "2t",
    "dis24",
    "sp",
    "ssrd",
    "strd",
    "tp",
    "swh",
    "year_progress_sin",
    "year_progress_cos",
]
levels = [0, 4, 8, 12, 16, 20, 24, 28, 32, 34]
input_duration = "2d"

[model]
latent_size = 512
gnn_msg_steps = 16
hidden_layers = 1
radius_query_fraction_edge_length = 0.6
# The weights are chosen the same way as GraphCast here, with those of surface variables about equal to 1/num_levels
# (except for 2m temperature?)
per_variable_weights = {zos = 0.1, mlotst = 0.1, thetao = 1.0, so = 1.0, uo = 1.0, vo = 1.0}
learnable_fourier_features = true

[mesh]
filepath = "data/geometry/uniform_coarse.msh"
mesh_size_tag_name = "MeshSize"
step = 0

[mask]
filepath = "data/dataset/dataset_tres-1d_res-0p25_levels-10_arco"
name = "glorys_mask"
level = 0
fill_value = 0.0

[dataset]
filepath = "data/dataset/dataset_tres-1d_res-0p25_levels-10_arco"
target_lead_times = "1d"
split_date = "2019-06-30T00:00:00"
local_batch_size = 1

# Multiprocessing dataloader is currently broken, we only use a multithreaded reader.
[dataset.read_options]
num_threads = 4
prefetch_buffer_size = 32

[policy]
names_which_can_be_saved = []
names_which_can_be_offloaded = ["positional_encoder", "graph_embedder", "message_passing", "graph_output"]
offload_src = "device"
offload_dst = "pinned_host"

[artifacts]
filepath = "data/dataset/dataset_tres-1d_res-0p25_levels-10_normalization"
skip_names = ["year_progress_cos", "year_progress_sin"]

[artifacts.mean_by_level]
path = '/inputs/location'

[[artifacts.mean_by_level.postprocess]]
name = 'fillna'
value = 0.0

[artifacts.stddev_by_level]
path = '/inputs/scale'

[[artifacts.stddev_by_level.postprocess]]
name = 'fillna'
value = 1.0

[[artifacts.stddev_by_level.postprocess]]
name = 'clip'
min = 1e-16

[artifacts.diffs_stddev_by_level]
path = '/residuals/scale'

[[artifacts.diffs_stddev_by_level.postprocess]]
name = 'fillna'
value = 1.0

[[artifacts.diffs_stddev_by_level.postprocess]]
name = 'clip'
min = 1e-16

[optimizer]
schedule_boundaries = [512]

[[optimizer.schedule]]
name = 'linear_schedule'
init_value = 0.0
end_value = 1.0e-3
transition_steps = 512

[[optimizer.schedule]]
name = 'cosine_decay_schedule'
init_value = 1.0e-3
decay_steps = 32640
alpha = 3.0e-4

[[optimizer.gradient_transformation]]
name = 'clip_by_global_norm'
max_norm = 32.0

[[optimizer.gradient_transformation]]
name = 'adamw'
b1 = 0.9
b2 = 0.95
weight_decay = 0.1

[checkpoints]
max_to_keep=3