seed = 42
local_batch_size = 4
jax_backend = "gpu"
training_steps = 32
sgd_step_size = 1e-4

[dataset]
filepath = "data/dataset/dataset_tres-1d_res-0p25_levels-10_arco"
timesteps = 3

[sampler]
num_epochs = 1
shuffle_dataset = true
seed = 42

[dataloader]

[policy]
names_which_can_be_saved = []
names_which_can_be_offloaded = ["embedder", "message_passing", "grid2mesh_gnn", "mesh_gnn", "mesh2grid_gnn"]
offload_src = "device"
offload_dst = "pinned_host"

[artifacts]
filepath = "data/dataset/dataset_tres-1d_res-0p25_levels-10_normalization"
